/** Textos oficiales de catálogos INSAL — causales, redenciones y reconocimientos. */

export const CAUSALES_DEMERITO = [
  ['A', 'NO SALUDAR AL ENTRAR O AL SALIR DEL AULA'],
  ['B', 'OMITIR POR FAVOR AL HACER UNA PETICIÓN'],
  ['C', 'OMITIR GRACIAS AL RECIBIR UN FAVOR, MATERIAL O ATENCIÓN'],
  ['D', 'USAR UN TONO GROSERO O IRRESPETUOSO HACIA COMPAÑEROS, DOCENTES O PERSONAL'],
]

export const OPCIONES_REDENCION = [
  ['A', 'CUMPLIR UNA SEMANA COMPLETA CON SALUDOS Y EXPRESIONES DE CORTESÍA EJEMPLARES'],
  ['B', 'APOYAR VOLUNTARIAMENTE EN ACTIVIDADES DE ORDEN Y LIMPIEZA ESCOLAR'],
  ['C', 'PARTICIPAR EN CAMPAÑAS DE VALORES ORGANIZADAS POR EL CENTRO EDUCATIVO'],
]

export const TIPOS_RECONOCIMIENTO = [
  ['A', 'MENCIÓN HONORÍFICA EN MURAL ESCOLAR DE CORTESÍA ESCOLAR'],
  ['B', 'OTORGAR DIPLOMAS O MENCIONES EN MURALES ESCOLARES'],
]
